version: "3"

services:
  server:
    container_name: server
    build: server/
    stdin_open: true
    tty: true
    command: bash server.sh
    depends_on:
      - client1
      - client2
      - client3
      - client4
    cap_add:
      - NET_ADMIN
    networks:
      testing_net:
        ipv4_address: 172.28.1.0
      
  client1:
    container_name: client1
    build: client/
    tty: true
    command: bash client.sh
    cap_add:
      - NET_ADMIN
    networks:
      testing_net:
        ipv4_address: 172.28.1.1
        
  client2:
    container_name: client2
    build: client/
    tty: true
    command: bash client.sh
    cap_add:
      - NET_ADMIN
    networks:
      testing_net:
        ipv4_address: 172.28.1.2
        
  client3:
    container_name: client3
    build: client/
    tty: true
    command: bash client.sh
    cap_add:
      - NET_ADMIN
    networks:
      testing_net:
        ipv4_address: 172.28.1.3
        
  client4:
    container_name: client4
    build: client/
    tty: true
    command: bash client.sh
    cap_add:
      - NET_ADMIN
    networks:
      testing_net:
        ipv4_address: 172.28.1.4
        
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

